"""Run-orchestration service contracts for Quant Factory."""

from orchestration.run_service import (
    FixtureRunService,
    RunLaunchResult,
    RunReproductionResult,
    RunEvent,
    RunServiceError,
    RunSummary,
)
from orchestration.research_launch_claims import (
    CANDIDATE_SCREENING_LAUNCH_CONTRACT,
    CANDIDATE_SCREENING_LAUNCH_POLICY,
    CANDIDATE_SCREENING_REQUEST_PROTOCOL_VERSION,
    DurableResearchLaunchService,
    FIXTURE_LAUNCH_CONTRACT,
    ResearchDispatchDecision,
    ResearchDispatchResult,
    ResearchLaunchClaim,
    ResearchLaunchConflictError,
    ResearchLaunchContentionError,
    ResearchLaunchError,
    ResearchLaunchIntegrityError,
    ResearchLaunchInvocationError,
    ResearchLaunchInvocationUnknownError,
    ResearchLaunchKeyError,
    ResearchLaunchRequest,
    new_dispatcher_instance_id,
    new_research_launch_key,
)
from orchestration.candidate_run_service import (
    CandidateRunService,
    CandidateScreeningAdapter,
    CandidateScreeningLaunchResult,
)

__all__ = [
    "FixtureRunService",
    "RunLaunchResult",
    "RunReproductionResult",
    "RunEvent",
    "RunServiceError",
    "RunSummary",
    "DurableResearchLaunchService",
    "FIXTURE_LAUNCH_CONTRACT",
    "CANDIDATE_SCREENING_LAUNCH_CONTRACT",
    "CANDIDATE_SCREENING_LAUNCH_POLICY",
    "CANDIDATE_SCREENING_REQUEST_PROTOCOL_VERSION",
    "ResearchDispatchDecision",
    "ResearchDispatchResult",
    "ResearchLaunchClaim",
    "ResearchLaunchConflictError",
    "ResearchLaunchContentionError",
    "ResearchLaunchError",
    "ResearchLaunchIntegrityError",
    "ResearchLaunchInvocationError",
    "ResearchLaunchInvocationUnknownError",
    "ResearchLaunchKeyError",
    "ResearchLaunchRequest",
    "new_dispatcher_instance_id",
    "new_research_launch_key",
    "CandidateRunService",
    "CandidateScreeningAdapter",
    "CandidateScreeningLaunchResult",
]
